### ISSUE TITLE
basic design prototype

### ISSUE THREAD

**Issue by stevenJoyce** [EvanGreaney/3rdYearGroupProject#2]
How the app will look

**Comment by EvanGreaney** [comment]
Please Find enclosed the proposed WireFrames for the Project and the projected look for the App

![BarCode Scanner](https://user-images.githubusercontent.com/37175022/74109976-337dc900-4b80-11ea-9871-7a32c0dc01b0.PNG)
![Drop Down  Menu](https://user-images.githubusercontent.com/37175022/74109977-37115000-4b80-11ea-8f91-8529f66bc473.PNG)
![Product Prices](https://user-images.githubusercontent.com/37175022/74109978-3973aa00-4b80-11ea-87fe-99827e5467c9.PNG)
![Product Info](https://user-images.githubusercontent.com/37175022/74109979-3aa4d700-4b80-11ea-8ae0-64f8981c4cfc.PNG)
